use_frameworks!

platform :ios, '10.0'

target 'LVFrameMini_Example' do
  pod 'LVFrameMini', :path => '../'

  target 'LVFrameMini_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
